<?php
require_once 'Mail.php';
function send_email($to, $headers, $body) {
  global $SMTPserver;
  global $SMTPPort;
  global $SMTPAuth;
  global $SMTPUsername;
  global $SMTPPassword;

  $smtp = Mail::factory('smtp', array(
      'host' => $SMTPserver,
      'port' => $SMTPPort,
      'auth' => $SMTPAuth,
      'username' =>  $SMTPUsername,
      'password' => $SMTPPassword));
  $mail = $smtp->send($to, $headers, $body);
  if (PEAR::isError($mail)) {
    echo("<p>" . $mail->getMessage() . "</p>");
  } else {
    echo("Email sent!");
  }
}

// sends email to users while the timeslot is deleted
function sendMailToParticipants($id){
  global $mysqli;
  $emails = Array();
  if (!($stmt = $mysqli->prepare("SELECT participant_email FROM signsup WHERE timeslot_id=?"))) {
    echo "Prepare failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $stmt->bind_param("i", $id);
  if (!$stmt->execute()) {
    echo "Execute failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $result = $stmt->get_result();
  while($row=$result->fetch_assoc()){
    $emails[] = $row['participant_email'];   
  }
  /* close statement */
  $stmt->close();
    
  if (!($stmt = $mysqli->prepare("SELECT title, hour_credit, location, researcher_email, etime,edate  FROM experiment INNER JOIN timeslot ON experiment.experiment_id=timeslot.experiment_id WHERE timeslot_id=?"))) {
    echo "Prepare failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $stmt->bind_param("i", $id);
  if (!$stmt->execute()) {
    echo "Execute failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $result2 = $stmt->get_result();

  $row2=$result->fetch_assoc();
  /* close statement */
  $stmt->close();
  //construct an email body
  $email= implode($emails,', ');
  $subject="FREUD Online:  signup canceled!";
  ///        
  $emailmessage="The following slot you have signed up for has been deleted:<br><br>\n";

  $emailmessage=$emailmessage."<table border='0'><tr><td>Title:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".$row2['title']."</td></tr>\n";
  $emailmessage=$emailmessage."<tr><td>Location:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".$row2['location']."</td></tr>\n";
  $emailmessage=$emailmessage."<tr><td>Hour/credit:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".$row2['hour_credit']."</td></tr>\n";

  $emailmessage=$emailmessage."<tr><td>Date:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".transformDateYearLast($row2['edate']).", ".dayofweek($row2['edate'])."</td></tr>\n";
  $emailmessage=$emailmessage."<tr><td>Time:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".time24to12($row2['etime'])."</td></tr></table>\n";

  $emailmessage=$emailmessage."<br>Thank you for your participation!<br>\n";


  $emailmessage=$emailmessage."<br><br><small>generated by UCITS</small><br>";    

  $headers = 'From: ' . $server_email_address . "\r\n";      
  $headers .= "Bcc: {$email}" . "\r\n";                   
  $headers .= 'Reply-To: '. $row2['researcher_email'] . "\r\n";
  //send an email
  mail($server_email_address,$subject,$emailmessage, $headers);

  $headers = array (
      'From' => $server_email_address,
      'Reply-To' => $row2['researcher_email'],
      'Bcc' => '$email',
      'Subject' => $subject);
  send_email($to,$headers,$emailmessage);
}


// send email to user with canceled signup
function sendMailToUser($id){ // signup id
  global $mysqli;
  if (!($stmt = $mysqli->prepare("SELECT participant_email FROM signsup WHERE sign_up_id=?"))) {
    echo "Prepare failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $stmt->bind_param("i", $id);
  if (!$stmt->execute()) {
    echo "Execute failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $result = $stmt->get_result();
  $emails = Array();
  $row = $result->fetch_assoc();
  $stmt->close();
  $email = $row['participant_email'];

  if (!($stmt = $mysqli->prepare("SELECT title, hour_credit, location, researcher_email, etime,edate 
			FROM experiment 
			INNER JOIN timeslot 
			ON experiment.experiment_id=timeslot.experiment_id 
			INNER JOIN signsup 
			ON signsup.timeslot_id = timeslot.timeslot_id
			WHERE signsup.sign_up_id=?"))) {
    echo "Prepare failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $stmt->bind_param("i", $id);
  if (!$stmt->execute()) {
    echo "Execute failed: (" . $mysqli->errno . ") " . $mysqli->error;
  }
  $result2 = $stmt->get_result();
  
  $row2 = $result->fetch_assoc();
  $stmt->close();
  //construct an email body
  //$email=$_SESSION['email'];
  $subject="FREUD Online:  signup canceled!";

  ///        
  $emailmessage="You have been removed from the following slot:<br><br>\n";

  $emailmessage=$emailmessage."<table border='0'><tr><td>Title:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".$row2['title']."</td></tr>\n";
  $emailmessage=$emailmessage."<tr><td>Location:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".$row2['location']."</td></tr>\n";
  $emailmessage=$emailmessage."<tr><td>Hour/credit:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".$row2['hour_credit']."</td></tr>\n";

  $emailmessage=$emailmessage."<tr><td>Date:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".transformDateYearLast($row2['edate']).", ".dayofweek($row2['edate'])."</td></tr>\n";
  $emailmessage=$emailmessage."<tr><td>Time:</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>\t".time24to12($row2['etime'])."</td></tr></table>\n";

  $emailmessage=$emailmessage."<br>If you don't expect this email, please contact the researcher at <a href='mailto: ".$row2['researcher_email']."'>".$row2['researcher_email']."</a> or reply to this email.\n";

  $emailmessage=$emailmessage."<br>Thank you for your participation!<br>\n";


  $emailmessage=$emailmessage."<br><br><small>generated by UCITS</small><br>";    

  $headers = 'From: '. $server_email_address . "\r\n";  
  $headers = 'Reply-To: '. $row2['researcher_email'] . "\r\n";
  $headers.= "Content-Type: text/html; charset=ISO-8859-1 ";
  $headers .= "MIME-Version: 1.0 "; 
  //send an email
  //echo $email.'<br /><br />'.$subject.'<br /><br />'.$emailmessage.'<br /><br />'.$headers;
  if($email!='') mail($email,$subject,$emailmessage, $headers);
}

function printTimeslot($id, $idmax)
{
  global $rememberFormValues;

  $hour="hour".$id;
  $minute="mimute".$id;
  $daypart="daypart".$id;
  $capacity="capacity".$id;

  echo "<label>Timeslot ".$id.":</label>";
  echo "<select name=\"".$hour."\">\n";

  for ($ii=1; $ii<=12;$ii++)
  {
    if ($ii<10) $ii="0".$ii;
    echo "<option value=\"".$ii."\"";
    if ($rememberFormValues!=0 && isset($_POST[$hour]) && $_POST[$hour]==$ii){echo " selected=\"yes\" ";}
    echo ">".$ii."</option>\n";
  }

  echo "</select>";
  echo "<select name=\"".$minute."\">\n";

  for ($ii=0; $ii<60;$ii+=5)
  {
    if ($ii<10) $ii="0".$ii;
    echo "        <option value=\"".$ii."\"";
    if ($rememberFormValues!=0 && isset($_POST[$minute]) && $_POST[$minute]==$ii){echo " selected=\"yes\" ";}
    echo ">".$ii."</option>\n";
  }

  echo "</select>\n";
  echo "<select name=\"".$daypart."\">\n";
  echo "<option value=\"am\""; if ($rememberFormValues!=0 && isset($_POST[$daypart]) && $_POST[$daypart]=="am"){echo " selected=\"yes\" ";} echo ">am</option>\n";
  echo "<option value=\"pm\""; if ($rememberFormValues!=0 && isset($_POST[$daypart]) && $_POST[$daypart]=="pm"){echo " selected=\"yes\" ";} echo ">pm</option>\n";
  echo "</select>\n";
  echo "<label>Capacity:</label>\n";
  echo "<select name=\"".$capacity."\">\n";
  for ($ii=1; $ii<=12;$ii++)
  {
    echo "<option value=\"".$ii."\"";
    if ($rememberFormValues!=0 && isset($_POST[$capacity]) && $_POST[$capacity]==$ii){echo " selected=\"yes\" ";}
    echo ">".$ii."</option>\n";
  }
  echo "</select>\n";
  echo "</td>\n";

  echo "<td>\n";
  if ($id==$idmax)
  {
    echo "<input type=\"submit\" name=\"addslot\" value =\"Make more slots\">\n";
    echo "<input type=\"submit\" name=\"removeslot\" value =\"Remove this slot\">\n";
    echo "<input type=\"hidden\" name=\"id\" value =\"".$id."\">\n";

  }else{
    echo " ";
  }
}

?>
